language: python
python:
  - "2.7"
  - "3.8"
# command to install dependencies
install:
  - pip install coverage
  - pip install retry
  - pip install retrying
# command to run tests
script: coverage.sh
